defaults:
  repositories:
    flags: "--verbose"
  forge_modules:
    flags: "--verbose"
  symlinks:
    flags: "--verbose"

fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    inifile: "puppetlabs/inifile"
  repositories:
    apache: "http://devops.ls.cbn/git/server-management/puppet-global/modules/cbntss-apache.git"
    pki: "http://devops.ls.cbn/git/server-management/puppet-global/modules/cbntss-pki.git"
  symlinks:
    "sync_ts_server": "#{source_dir}"
