language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
rvm:
  - 2.1.9
script: bundle exec rake test
env:
  - PUPPET_VERSION="~>5.5.14"

notifications:
  email:
    on_success: always
    on_failure: never
