source 'https://rubygems.org'

  gem 'puppetlabs_spec_helper'
  gem 'puppet'
  gem 'rake', '>= 0.9.0'
  gem 'rspec'
  gem 'rspec-puppet'
  gem 'puppet-lint'
  gem 'rspec-puppet-facts'
  gem 'rspec-fixture'
