source 'https://rubygems.org'

  gem 'puppetlabs_spec_helper'
  gem 'puppet'
  gem 'rake', '>= 0.9.0'
  gem 'rspec'
  gem 'rspec-puppet'
  gem 'mocha'
  gem 'travis'
  gem 'travis-lint'
  gem 'rspec-system'
  gem 'rspec-system-puppet'
  gem 'puppet-lint'
